spring.application.name=Leave-Service
server.port=8083

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

employee.service.url=http://employee-service:8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mySecretKeyForJwtGeneration123456789
jwt.expiration=86400000
